apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-wmqo
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0035-tenant/tkrw-pr712-0075-0035-app/devfile-sample-wmqo@sha256:5ba06a894139eb1c0aa2b595a5c9c7acc3990a1307ff22e23eb4f9dc2db2a793
        name: my-nodejs
        resources: {}
status: {}
